"use client";

import Link from "next/link";
import { useEffect, useRef } from "react";
import { toast } from "sonner";
import { ArrowLeft, Archive, PauseCircle, SearchX, Loader2 } from "lucide-react";

import { Avatar, PlatformChip, PriorityBadge, StatusBadge } from "@/components/app/badges";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { ConversationTimeline } from "@/components/conversations/timeline";
import { AiAnalysisCard } from "@/components/conversations/ai-panel";
import { DraftCard } from "@/components/conversations/draft-card";
import {
  useApproveDraft,
  useConversationDetail,
  useGenerateDraft,
  useRegenerateDraft,
  useSaveDraft,
  useSendDraft,
  useUpdateConversation,
} from "@/hooks/use-data";

export function ConversationDetailPage({ id }: { id: string }) {
  const { data: conversation, isLoading, isError } = useConversationDetail(id);
  const updateConversation = useUpdateConversation();
  const generateDraft = useGenerateDraft();
  const regenerateDraft = useRegenerateDraft();
  const approveDraft = useApproveDraft();
  const saveDraft = useSaveDraft();
  const sendDraft = useSendDraft();
  const autoGeneratedRef = useRef(false);

  useEffect(() => {
    autoGeneratedRef.current = false;
  }, [id]);

  useEffect(() => {
    if (conversation && !conversation.draft.id && !autoGeneratedRef.current && !generateDraft.isPending) {
      autoGeneratedRef.current = true;
      generateDraft.mutate(
        { conversationId: id },
        {
          onError: () => {
            autoGeneratedRef.current = false;
          },
        },
      );
    }
  }, [conversation, id, generateDraft]);

  if (isLoading) {
    return (
      <div className="px-4 py-6 lg:px-8">
        <div className="flex items-center gap-3">
          <Skeleton className="size-13 rounded-full" />
          <div className="space-y-2">
            <Skeleton className="h-5 w-48" />
            <Skeleton className="h-3.5 w-72" />
          </div>
        </div>
        <div className="mt-8 grid grid-cols-1 gap-6 lg:grid-cols-5">
          <div className="space-y-3 lg:col-span-3">
            <Skeleton className="h-32 w-full" />
            <Skeleton className="h-32 w-full" />
          </div>
          <div className="space-y-3 lg:col-span-2">
            <Skeleton className="h-56 w-full" />
            <Skeleton className="h-64 w-full" />
          </div>
        </div>
      </div>
    );
  }

  if (isError || !conversation) {
    return (
      <div className="flex flex-col items-center justify-center gap-4 px-6 py-24 text-center">
        <div className="grid size-14 place-items-center rounded-full border border-border bg-surface-2">
          <SearchX className="size-6 text-subtle" />
        </div>
        <div>
          <p className="text-sm font-semibold text-foreground">Conversation not found</p>
          <p className="mt-1 max-w-sm text-sm text-muted-foreground">
            This conversation may have been archived or the link is out of date.
          </p>
        </div>
        <Button asChild variant="secondary" size="sm">
          <Link href="/conversations">
            <ArrowLeft className="mr-1.5 size-4" />
            Back to conversations
          </Link>
        </Button>
      </div>
    );
  }

  const draftId = conversation.draft.id;

  const handlePause = () => {
    updateConversation.mutate(
      { id, data: { status: "paused" } },
      {
        onSuccess: () => toast.success(`Tracking paused for ${conversation.name}`),
        onError: (error) => toast.error(error instanceof Error ? error.message : "Failed to pause"),
      },
    );
  };

  const handleArchive = () => {
    updateConversation.mutate(
      { id, data: { status: "archived" } },
      {
        onSuccess: () => toast.success(`${conversation.subject} archived`),
        onError: (error) => toast.error(error instanceof Error ? error.message : "Failed to archive"),
      },
    );
  };

  const handleGenerate = () => {
    generateDraft.mutate(
      { conversationId: id },
      {
        onSuccess: () => toast.success("Follow-up draft generated"),
        onError: (error) => toast.error(error instanceof Error ? error.message : "Generation failed"),
      },
    );
  };

  const handleRegenerate = () => {
    if (!draftId) return;
    regenerateDraft.mutate(
      { draftId },
      {
        onSuccess: () => toast.success("Draft regenerated with a fresh variant"),
        onError: (error) => toast.error(error instanceof Error ? error.message : "Regeneration failed"),
      },
    );
  };

  const handleApprove = () => {
    if (!draftId) return;
    approveDraft.mutate(draftId, {
      onSuccess: () => toast.success("Draft approved"),
      onError: (error) => toast.error(error instanceof Error ? error.message : "Approval failed"),
    });
  };

  const handleSave = (body: string, subject: string) => {
    if (!draftId) return;
    saveDraft.mutate(
      { draftId, subject, body },
      {
        onSuccess: () => toast.success("Draft saved"),
        onError: (error) => toast.error(error instanceof Error ? error.message : "Save failed"),
      },
    );
  };

  const handleSend = async (editedBody?: string, editedSubject?: string) => {
    if (!draftId) return;
    if (editedBody !== undefined && editedSubject !== undefined) {
      await saveDraft.mutateAsync({ draftId, subject: editedSubject, body: editedBody });
    }
    sendDraft.mutate(
      { draftId, conversationId: id },
      {
        onSuccess: () => toast.success("Follow-up sent successfully"),
        onError: (error) => toast.error(error instanceof Error ? error.message : "Send failed"),
      },
    );
  };

  return (
    <div>
      <div className="border-b border-border px-4 py-6 lg:px-8">
        <Link
          href="/conversations"
          className="inline-flex items-center gap-1.5 text-xs font-medium text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="size-3.5" />
          Back to conversations
        </Link>

        <div className="mt-4 flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
          <div className="flex items-start gap-3">
            <Avatar initials={conversation.initials} hue={conversation.avatarHue} size={52} />
            <div>
              <div className="flex flex-wrap items-center gap-2">
                <h1 className="font-display text-xl font-semibold text-foreground">{conversation.name}</h1>
                <span className="text-sm text-subtle">· {conversation.company}</span>
              </div>
              <p className="text-xs text-subtle">{conversation.handle}</p>
              <p className="mt-1.5 text-sm text-muted-foreground">{conversation.subject}</p>
              <div className="mt-2.5 flex flex-wrap items-center gap-1.5">
                <StatusBadge status={conversation.status} />
                <PriorityBadge priority={conversation.priority} />
                <PlatformChip platform={conversation.platform} />
                <span className="inline-flex items-center rounded-full border border-border bg-surface-2 px-2 py-0.5 text-[11px] font-medium text-muted-foreground">
                  {conversation.daysWaiting}d waiting
                </span>
                <span className="inline-flex items-center rounded-full border border-border bg-surface-2 px-2 py-0.5 text-[11px] font-medium text-muted-foreground">
                  {conversation.value}
                </span>
              </div>
            </div>
          </div>

          <div className="flex shrink-0 gap-2">
            <Button
              variant="secondary"
              size="sm"
              className="gap-1.5"
              onClick={handlePause}
              disabled={updateConversation.isPending}
            >
              <PauseCircle className="size-3.5" />
              Pause
            </Button>
            <Button
              variant="secondary"
              size="sm"
              className="gap-1.5"
              onClick={handleArchive}
              disabled={updateConversation.isPending}
            >
              <Archive className="size-3.5" />
              Archive
            </Button>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-6 px-4 py-6 lg:grid-cols-5 lg:px-8">
        <div className="lg:col-span-3">
          <h2 className="mb-4 font-display text-sm font-semibold uppercase tracking-wide text-subtle">
            Conversation timeline
          </h2>
          <ConversationTimeline events={conversation.timeline} />
        </div>

        <div className="flex flex-col gap-5 lg:col-span-2 lg:sticky lg:top-20 lg:self-start">
          <AiAnalysisCard analysis={conversation.analysis} />
          {generateDraft.isPending && !conversation.draft.id && (
            <div className="flex items-center gap-2 rounded-lg border border-border bg-card px-4 py-3 text-sm text-muted-foreground">
              <Loader2 className="size-4 animate-spin text-primary" />
              Analyzing conversation... Generating follow-up...
            </div>
          )}
          <DraftCard
            draft={conversation.draft}
            onGenerate={handleGenerate}
            onRegenerate={handleRegenerate}
            onApprove={handleApprove}
            onSave={handleSave}
            onSend={handleSend}
            generating={generateDraft.isPending}
            regenerating={regenerateDraft.isPending}
            approving={approveDraft.isPending}
            sending={sendDraft.isPending}
          />
        </div>
      </div>
    </div>
  );
}
